<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Caleb Lee">

<title>Group Comparison in R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="02_group_comparison_R_files/libs/clipboard/clipboard.min.js"></script>
<script src="02_group_comparison_R_files/libs/quarto-html/quarto.js"></script>
<script src="02_group_comparison_R_files/libs/quarto-html/popper.min.js"></script>
<script src="02_group_comparison_R_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="02_group_comparison_R_files/libs/quarto-html/anchor.min.js"></script>
<link href="02_group_comparison_R_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="02_group_comparison_R_files/libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="02_group_comparison_R_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="02_group_comparison_R_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="02_group_comparison_R_files/libs/bootstrap/bootstrap-973236bd072d72a04ee9cd82dcc9cb29.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Group Comparison in R</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Caleb Lee </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="creating-continent-groups" class="level2">
<h2 class="anchored" data-anchor-id="creating-continent-groups">Creating continent groups</h2>
<section id="import-libraries-and-sample" class="level3">
<h3 class="anchored" data-anchor-id="import-libraries-and-sample">Import libraries and sample</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span> (broom)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>bigfive <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">'../data/cleaned/cleaned_bigfive_v1.csv'</span>) <span class="co"># read_csv() - reads csv into an R data frame</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 602587 Columns: 126
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr    (3): country, lat_appx_lots_of_err, long_appx_lots_of_err
dbl  (122): EXT1, EXT2, EXT3, EXT4, EXT5, EXT6, EXT7, EXT8, EXT9, EXT10, EST...
dttm   (1): dateload

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Sampling</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>) <span class="co"># same random seed for reproducibility</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>bigfive_sample <span class="ot">&lt;-</span> bigfive <span class="sc">%&gt;%</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sample_n</span>(<span class="dv">5000</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="creating-continent-groups-filtering-for-none-and-minor-countries." class="level3">
<h3 class="anchored" data-anchor-id="creating-continent-groups-filtering-for-none-and-minor-countries.">Creating Continent groups; filtering for NONE and minor countries.</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Checking which countries are present</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>bigfive_sample <span class="sc">%&gt;%</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">count</span>(country, <span class="at">sort =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">print</span> (<span class="at">n =</span> <span class="cn">Inf</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 107 × 2
    country     n
    &lt;chr&gt;   &lt;int&gt;
  1 US       2473
  2 GB        372
  3 CA        320
  4 AU        249
  5 DE         91
  6 IN         90
  7 PH         82
  8 MX         80
  9 NONE       67
 10 SE         58
 11 NL         55
 12 MY         52
 13 NO         52
 14 FR         49
 15 ID         45
 16 NZ         44
 17 BR         41
 18 RO         37
 19 FI         36
 20 SG         33
 21 ES         30
 22 AR         27
 23 IT         27
 24 DK         26
 25 IE         25
 26 BE         24
 27 PL         22
 28 RU         20
 29 ZA         20
 30 PT         18
 31 CO         17
 32 AT         16
 33 TR         16
 34 HK         15
 35 JP         15
 36 SA         15
 37 AE         14
 38 HR         13
 39 HU         13
 40 IL         13
 41 KR         13
 42 GR         12
 43 PK         12
 44 BG         11
 45 TH         11
 46 CL         10
 47 CZ         10
 48 EC         10
 49 EG         10
 50 KE          9
 51 RS          9
 52 CH          8
 53 PE          8
 54 VN          8
 55 VE          7
 56 LT          6
 57 MA          6
 58 SK          6
 59 UA          6
 60 BA          5
 61 CN          5
 62 DO          5
 63 NP          5
 64 AL          4
 65 CR          4
 66 EE          4
 67 GE          4
 68 KH          4
 69 LB          4
 70 MK          4
 71 TW          4
 72 CY          3
 73 IS          3
 74 KZ          3
 75 LV          3
 76 PR          3
 77 TN          3
 78 TT          3
 79 BB          2
 80 BD          2
 81 BN          2
 82 BO          2
 83 GU          2
 84 IR          2
 85 JO          2
 86 KW          2
 87 LK          2
 88 MD          2
 89 MU          2
 90 OM          2
 91 PY          2
 92 QA          2
 93 AD          1
 94 BH          1
 95 BM          1
 96 BW          1
 97 ET          1
 98 HN          1
 99 IQ          1
100 JE          1
101 JM          1
102 ME          1
103 MO          1
104 NG          1
105 PG          1
106 SD          1
107 ZW          1</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Sort countries into continents (same as python)</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Continent group creation</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>north_america <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">'US'</span>, <span class="st">'CA'</span>, <span class="st">'MX'</span>, <span class="st">'PR'</span>, <span class="st">'CR'</span>, <span class="st">'DO'</span>, <span class="st">'JM'</span>, <span class="st">'TT'</span>, <span class="st">'BM'</span>, <span class="st">'HN'</span>)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>south_america <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">'BR'</span>, <span class="st">'AR'</span>, <span class="st">'CL'</span>, <span class="st">'CO'</span>, <span class="st">'PE'</span>, <span class="st">'VE'</span>, <span class="st">'EC'</span>, <span class="st">'BO'</span>, <span class="st">'PY'</span>)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>europe <span class="ot">&lt;-</span> <span class="fu">c</span>( <span class="st">'RO'</span>,<span class="st">'GB'</span>, <span class="st">'IE'</span>, <span class="st">'DE'</span>, <span class="st">'FR'</span>, <span class="st">'NL'</span>, <span class="st">'SE'</span>, <span class="st">'NO'</span>, <span class="st">'FI'</span>, <span class="st">'DK'</span>, <span class="st">'BE'</span>, <span class="st">'PL'</span>,</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>             <span class="st">'IT'</span>, <span class="st">'PT'</span>, <span class="st">'ES'</span>, <span class="st">'CH'</span>, <span class="st">'AT'</span>, <span class="st">'CZ'</span>, <span class="st">'HU'</span>, <span class="st">'SK'</span>, <span class="st">'EE'</span>, <span class="st">'LT'</span>, <span class="st">'UA'</span>,</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>             <span class="st">'BG'</span>, <span class="st">'GR'</span>, <span class="st">'RS'</span>, <span class="st">'HR'</span>, <span class="st">'CY'</span>, <span class="st">'MK'</span>, <span class="st">'BA'</span>, <span class="st">'IS'</span>, <span class="st">'JE'</span>, <span class="st">'LV'</span>, <span class="st">'MD'</span>,</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>             <span class="st">'ME'</span>, <span class="st">'AD'</span>, <span class="st">'AL'</span>)</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>asia <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">'IN'</span>, <span class="st">'PH'</span>, <span class="st">'MY'</span>, <span class="st">'SG'</span>, <span class="st">'ID'</span>, <span class="st">'PK'</span>, <span class="st">'HK'</span>, <span class="st">'JP'</span>, <span class="st">'KR'</span>, <span class="st">'VN'</span>, <span class="st">'TH'</span>,</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>          <span class="st">'IR'</span>, <span class="st">'LB'</span>, <span class="st">'TW'</span>, <span class="st">'AE'</span>, <span class="st">'IL'</span>, <span class="st">'JO'</span>, <span class="st">'NP'</span>, <span class="st">'CN'</span>, <span class="st">'KH'</span>, <span class="st">'QA'</span>, <span class="st">'BN'</span>,</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>          <span class="st">'KZ'</span>, <span class="st">'MO'</span>, <span class="st">'OM'</span>, <span class="st">'BD'</span>, <span class="st">'IQ'</span>, <span class="st">'GE'</span>, <span class="st">'BH'</span>, <span class="st">'KW'</span>, <span class="st">'LK'</span>, <span class="st">'SA'</span>)</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>oceania <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">'AU'</span>, <span class="st">'NZ'</span>, <span class="st">'PG'</span>, <span class="st">'GU'</span>)</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>bigfive_sample <span class="ot">&lt;-</span> bigfive_sample <span class="sc">%&gt;%</span></span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>    <span class="co"># filtering NONE entries</span></span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(country <span class="sc">!=</span> <span class="st">'NONE'</span>) <span class="sc">%&gt;%</span></span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(</span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>        <span class="at">continent =</span> <span class="fu">case_when</span>(</span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>            country <span class="sc">%in%</span> north_america <span class="sc">~</span> <span class="st">'NA'</span>,</span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>            country <span class="sc">%in%</span> south_america <span class="sc">~</span> <span class="st">'SA'</span>,</span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>            country <span class="sc">%in%</span> europe <span class="sc">~</span> <span class="st">'EU'</span>,</span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a>            country <span class="sc">%in%</span> asia <span class="sc">~</span> <span class="st">'AS'</span>,</span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a>            country <span class="sc">%in%</span> oceania <span class="sc">~</span> <span class="st">'OC'</span>,</span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a>            <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">'Other'</span></span>
<span id="cb8-26"><a href="#cb8-26" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb8-27"><a href="#cb8-27" aria-hidden="true" tabindex="-1"></a>    ) </span>
<span id="cb8-28"><a href="#cb8-28" aria-hidden="true" tabindex="-1"></a>bigfive_sample <span class="sc">%&gt;%</span></span>
<span id="cb8-29"><a href="#cb8-29" aria-hidden="true" tabindex="-1"></a>    <span class="fu">count</span>(continent, <span class="at">sort =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 2
  continent     n
  &lt;chr&gt;     &lt;int&gt;
1 NA         2891
2 EU         1063
3 AS          466
4 OC          296
5 SA          124
6 Other        93</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># What countries are in Other</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>bigfive_sample <span class="sc">%&gt;%</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(continent <span class="sc">==</span> <span class="st">'Other'</span>) <span class="sc">%&gt;%</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(country, <span class="at">sort =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 14 × 2
   country     n
   &lt;chr&gt;   &lt;int&gt;
 1 RU         20
 2 ZA         20
 3 TR         16
 4 EG         10
 5 KE          9
 6 MA          6
 7 TN          3
 8 BB          2
 9 MU          2
10 BW          1
11 ET          1
12 NG          1
13 SD          1
14 ZW          1</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Excluded a bunch of African countries and transcontinental countries (RU, TR) due to low n</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>bigfive_sample <span class="ot">&lt;-</span> bigfive_sample <span class="sc">%&gt;%</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(continent <span class="sc">!=</span> <span class="st">'Other'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="one-way-anova" class="level3">
<h3 class="anchored" data-anchor-id="one-way-anova">One-way ANOVA</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Group means for Openness</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>bigfive_sample <span class="sc">%&gt;%</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(continent) <span class="sc">%&gt;%</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>(</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">mean =</span> <span class="fu">mean</span> (Openness, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>    )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 2
  continent  mean
  &lt;chr&gt;     &lt;dbl&gt;
1 AS         3.22
2 EU         3.35
3 NA         3.32
4 OC         3.31
5 SA         3.36</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># One-way ANOVA for Openness</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>openness_anova <span class="ot">&lt;-</span> <span class="fu">aov</span>(Openness <span class="sc">~</span> continent, <span class="at">data =</span> bigfive_sample)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>anova_tidy <span class="ot">&lt;-</span> <span class="fu">tidy</span>(openness_anova)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(openness_anova)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Df Sum Sq Mean Sq F value  Pr(&gt;F)    
continent      4    6.3  1.5666   11.75 1.7e-09 ***
Residuals   4835  644.8  0.1334                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(anova_tidy, <span class="at">caption =</span> <span class="st">"Table: ANOVA for Openness by Continent"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Table: ANOVA for Openness by Continent</caption>
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">sumsq</th>
<th style="text-align: right;">meansq</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">continent</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">6.266247</td>
<td style="text-align: right;">1.5665617</td>
<td style="text-align: right;">11.74635</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Residuals</td>
<td style="text-align: right;">4835</td>
<td style="text-align: right;">644.823569</td>
<td style="text-align: right;">0.1333658</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Tukey HSD for Openness</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(openness_anova)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = Openness ~ continent, data = bigfive_sample)

$continent
             diff         lwr        upr     p adj
EU-AS  0.13302359  0.07765814 0.18838904 0.0000000
NA-AS  0.10901161  0.05926617 0.15875706 0.0000000
OC-AS  0.09388557  0.01981710 0.16795404 0.0049632
SA-AS  0.14686072  0.04616364 0.24755780 0.0006681
NA-EU -0.02401198 -0.05975756 0.01173360 0.3545073
OC-EU -0.03913802 -0.10463057 0.02635453 0.4776702
SA-EU  0.01383713 -0.08073051 0.10840478 0.9946504
OC-NA -0.01512604 -0.07594176 0.04568967 0.9610739
SA-NA  0.03784911 -0.05354190 0.12924011 0.7906036
SA-OC  0.05297515 -0.05362618 0.15957648 0.6559130</code></pre>
</div>
</div>
<section id="review-again-tomorrow" class="level4">
<h4 class="anchored" data-anchor-id="review-again-tomorrow">Review again tomorrow</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># One-way ANOVA result in knitr::kable:</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit ANOVA model</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>openness_anova <span class="ot">&lt;-</span> <span class="fu">aov</span>(Openness <span class="sc">~</span> continent, <span class="at">data =</span> bigfive_sample)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Tidy ANOVA result</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>anova_tidy <span class="ot">&lt;-</span> <span class="fu">tidy</span>(openness_anova)</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Display in table</span></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>  anova_tidy,</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">"Table 1. One-way ANOVA for Openness by Continent"</span>,</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">digits =</span> <span class="dv">4</span></span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Table 1. One-way ANOVA for Openness by Continent</caption>
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">sumsq</th>
<th style="text-align: right;">meansq</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">continent</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">6.2662</td>
<td style="text-align: right;">1.5666</td>
<td style="text-align: right;">11.7464</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Residuals</td>
<td style="text-align: right;">4835</td>
<td style="text-align: right;">644.8236</td>
<td style="text-align: right;">0.1334</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Tukey HSD in knitr::kable:</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>openness_tukey <span class="ot">&lt;-</span> <span class="fu">TukeyHSD</span>(openness_anova)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert to dataframe</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>tukey_df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(openness_tukey<span class="sc">$</span>continent)</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Add comparison pair as a column</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>tukey_df<span class="sc">$</span>comparison <span class="ot">&lt;-</span> <span class="fu">rownames</span>(tukey_df)</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Reorder columns for clarity</span></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>tukey_df <span class="ot">&lt;-</span> tukey_df <span class="sc">%&gt;%</span></span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(comparison, diff, lwr, upr, <span class="st">`</span><span class="at">p adj</span><span class="st">`</span>)</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Display nicely</span></span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>  tukey_df,</span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">"Table 2. Tukey HSD Post-Hoc Test for Openness by Continent"</span>,</span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">digits =</span> <span class="dv">4</span></span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Table 2. Tukey HSD Post-Hoc Test for Openness by Continent</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">comparison</th>
<th style="text-align: right;">diff</th>
<th style="text-align: right;">lwr</th>
<th style="text-align: right;">upr</th>
<th style="text-align: right;">p adj</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">EU-AS</td>
<td style="text-align: left;">EU-AS</td>
<td style="text-align: right;">0.1330</td>
<td style="text-align: right;">0.0777</td>
<td style="text-align: right;">0.1884</td>
<td style="text-align: right;">0.0000</td>
</tr>
<tr class="even">
<td style="text-align: left;">NA-AS</td>
<td style="text-align: left;">NA-AS</td>
<td style="text-align: right;">0.1090</td>
<td style="text-align: right;">0.0593</td>
<td style="text-align: right;">0.1588</td>
<td style="text-align: right;">0.0000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">OC-AS</td>
<td style="text-align: left;">OC-AS</td>
<td style="text-align: right;">0.0939</td>
<td style="text-align: right;">0.0198</td>
<td style="text-align: right;">0.1680</td>
<td style="text-align: right;">0.0050</td>
</tr>
<tr class="even">
<td style="text-align: left;">SA-AS</td>
<td style="text-align: left;">SA-AS</td>
<td style="text-align: right;">0.1469</td>
<td style="text-align: right;">0.0462</td>
<td style="text-align: right;">0.2476</td>
<td style="text-align: right;">0.0007</td>
</tr>
<tr class="odd">
<td style="text-align: left;">NA-EU</td>
<td style="text-align: left;">NA-EU</td>
<td style="text-align: right;">-0.0240</td>
<td style="text-align: right;">-0.0598</td>
<td style="text-align: right;">0.0117</td>
<td style="text-align: right;">0.3545</td>
</tr>
<tr class="even">
<td style="text-align: left;">OC-EU</td>
<td style="text-align: left;">OC-EU</td>
<td style="text-align: right;">-0.0391</td>
<td style="text-align: right;">-0.1046</td>
<td style="text-align: right;">0.0264</td>
<td style="text-align: right;">0.4777</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SA-EU</td>
<td style="text-align: left;">SA-EU</td>
<td style="text-align: right;">0.0138</td>
<td style="text-align: right;">-0.0807</td>
<td style="text-align: right;">0.1084</td>
<td style="text-align: right;">0.9947</td>
</tr>
<tr class="even">
<td style="text-align: left;">OC-NA</td>
<td style="text-align: left;">OC-NA</td>
<td style="text-align: right;">-0.0151</td>
<td style="text-align: right;">-0.0759</td>
<td style="text-align: right;">0.0457</td>
<td style="text-align: right;">0.9611</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SA-NA</td>
<td style="text-align: left;">SA-NA</td>
<td style="text-align: right;">0.0378</td>
<td style="text-align: right;">-0.0535</td>
<td style="text-align: right;">0.1292</td>
<td style="text-align: right;">0.7906</td>
</tr>
<tr class="even">
<td style="text-align: left;">SA-OC</td>
<td style="text-align: left;">SA-OC</td>
<td style="text-align: right;">0.0530</td>
<td style="text-align: right;">-0.0536</td>
<td style="text-align: right;">0.1596</td>
<td style="text-align: right;">0.6559</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Looping for all traits</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>traits <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">'Openness'</span>, <span class="st">'Conscientiousness'</span>, <span class="st">'Extraversion'</span>, <span class="st">'Agreeableness'</span>, <span class="st">'Neuroticism'</span>)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (trait <span class="cf">in</span> traits) {</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cat</span>(<span class="st">'</span><span class="sc">\n\n</span><span class="st">### ANOVA for'</span>, trait, <span class="st">'by Continent ###</span><span class="sc">\n\n</span><span class="st">'</span>)</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Group means</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>    means <span class="ot">&lt;-</span> bigfive_sample <span class="sc">%&gt;%</span></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>        <span class="fu">group_by</span>(continent) <span class="sc">%&gt;%</span></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>        <span class="fu">summarize</span>(</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>            <span class="at">mean =</span> <span class="fu">mean</span>(.data[[trait]], <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">print</span>(means)</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>    <span class="co"># ANOVA</span></span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>    model <span class="ot">&lt;-</span> <span class="fu">aov</span>(<span class="fu">as.formula</span>(<span class="fu">paste</span>(trait, <span class="st">'~ continent'</span>)), <span class="at">data =</span> bigfive_sample)</span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">print</span> (<span class="fu">summary</span>(model))</span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Tukey HSD</span></span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cat</span>(<span class="st">'</span><span class="sc">\n</span><span class="st">Tukey HSD:</span><span class="sc">\n</span><span class="st">'</span>)</span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a>    <span class="fu">print</span>(<span class="fu">TukeyHSD</span>(model))</span>
<span id="cb22-22"><a href="#cb22-22" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>

### ANOVA for Openness by Continent ###

# A tibble: 5 × 2
  continent  mean
  &lt;chr&gt;     &lt;dbl&gt;
1 AS         3.22
2 EU         3.35
3 NA         3.32
4 OC         3.31
5 SA         3.36
              Df Sum Sq Mean Sq F value  Pr(&gt;F)    
continent      4    6.3  1.5666   11.75 1.7e-09 ***
Residuals   4835  644.8  0.1334                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Tukey HSD:
  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = as.formula(paste(trait, "~ continent")), data = bigfive_sample)

$continent
             diff         lwr        upr     p adj
EU-AS  0.13302359  0.07765814 0.18838904 0.0000000
NA-AS  0.10901161  0.05926617 0.15875706 0.0000000
OC-AS  0.09388557  0.01981710 0.16795404 0.0049632
SA-AS  0.14686072  0.04616364 0.24755780 0.0006681
NA-EU -0.02401198 -0.05975756 0.01173360 0.3545073
OC-EU -0.03913802 -0.10463057 0.02635453 0.4776702
SA-EU  0.01383713 -0.08073051 0.10840478 0.9946504
OC-NA -0.01512604 -0.07594176 0.04568967 0.9610739
SA-NA  0.03784911 -0.05354190 0.12924011 0.7906036
SA-OC  0.05297515 -0.05362618 0.15957648 0.6559130



### ANOVA for Conscientiousness by Continent ###

# A tibble: 5 × 2
  continent  mean
  &lt;chr&gt;     &lt;dbl&gt;
1 AS         3.14
2 EU         3.11
3 NA         3.16
4 OC         3.08
5 SA         3.17
              Df Sum Sq Mean Sq F value   Pr(&gt;F)    
continent      4    2.9  0.7305   5.275 0.000308 ***
Residuals   4835  669.5  0.1385                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Tukey HSD:
  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = as.formula(paste(trait, "~ continent")), data = bigfive_sample)

$continent
              diff          lwr         upr     p adj
EU-AS -0.030659442 -0.087074823  0.02575594 0.5736278
NA-AS  0.015496516 -0.035192287  0.06618532 0.9200185
OC-AS -0.062787090 -0.138260164  0.01268598 0.1547914
SA-AS  0.022729475 -0.079877191  0.12533614 0.9744266
NA-EU  0.046155959  0.009732513  0.08257940 0.0049800
OC-EU -0.032127647 -0.098862178  0.03460688 0.6826874
SA-EU  0.053388918 -0.042972073  0.14974991 0.5547187
OC-NA -0.078283606 -0.140252608 -0.01631460 0.0051743
SA-NA  0.007232959 -0.085891152  0.10035707 0.9995521
SA-OC  0.085516565 -0.023106316  0.19413945 0.1999259



### ANOVA for Extraversion by Continent ###

# A tibble: 5 × 2
  continent  mean
  &lt;chr&gt;     &lt;dbl&gt;
1 AS         3.09
2 EU         2.99
3 NA         3.03
4 OC         3.02
5 SA         2.96
              Df Sum Sq Mean Sq F value   Pr(&gt;F)    
continent      4    3.6  0.9087   8.132 1.56e-06 ***
Residuals   4835  540.3  0.1117                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Tukey HSD:
  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = as.formula(paste(trait, "~ continent")), data = bigfive_sample)

$continent
             diff          lwr          upr     p adj
EU-AS -0.09349198 -0.144171412 -0.042812547 0.0000050
NA-AS -0.05406404 -0.099599137 -0.008528944 0.0105698
OC-AS -0.06476337 -0.132562833  0.003036096 0.0692870
SA-AS -0.13276686 -0.224941145 -0.040592566 0.0008175
NA-EU  0.03942794  0.006707792  0.072148086 0.0089872
OC-EU  0.02872861 -0.031220788  0.088678010 0.6864572
SA-EU -0.03927488 -0.125838510  0.047288757 0.7290051
OC-NA -0.01069933 -0.066367726  0.044969070 0.9848986
SA-NA -0.07870282 -0.162358674  0.004953044 0.0766707
SA-OC -0.06800349 -0.165582303  0.029575328 0.3164391



### ANOVA for Agreeableness by Continent ###

# A tibble: 5 × 2
  continent  mean
  &lt;chr&gt;     &lt;dbl&gt;
1 AS         3.27
2 EU         3.13
3 NA         3.16
4 OC         3.15
5 SA         3.12
              Df Sum Sq Mean Sq F value   Pr(&gt;F)    
continent      4    6.9  1.7180   14.93 3.94e-12 ***
Residuals   4835  556.4  0.1151                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Tukey HSD:
  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = as.formula(paste(trait, "~ continent")), data = bigfive_sample)

$continent
              diff           lwr         upr     p adj
EU-AS -0.142164253 -0.1935916730 -0.09073683 0.0000000
NA-AS -0.109507677 -0.1557148348 -0.06330052 0.0000000
OC-AS -0.115656536 -0.1844566662 -0.04685641 0.0000453
SA-AS -0.145386266 -0.2389209733 -0.05185156 0.0002192
NA-EU  0.032656576 -0.0005464944  0.06585965 0.0564872
OC-EU  0.026507717 -0.0343264870  0.08734192 0.7577417
SA-EU -0.003222013 -0.0910632558  0.08461923 0.9999774
OC-NA -0.006148859 -0.0626388774  0.05034116 0.9983068
SA-NA -0.035878589 -0.1207691404  0.04901196 0.7778997
SA-OC -0.029729730 -0.1287487291  0.06928927 0.9247769



### ANOVA for Neuroticism by Continent ###

# A tibble: 5 × 2
  continent  mean
  &lt;chr&gt;     &lt;dbl&gt;
1 AS         2.82
2 EU         2.91
3 NA         2.99
4 OC         2.97
5 SA         2.78
              Df Sum Sq Mean Sq F value   Pr(&gt;F)    
continent      4   19.4   4.847   11.69 1.91e-09 ***
Residuals   4835 2005.6   0.415                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Tukey HSD:
  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = as.formula(paste(trait, "~ continent")), data = bigfive_sample)

$continent
             diff          lwr          upr     p adj
EU-AS  0.09499453 -0.002647434  0.192636493 0.0610501
NA-AS  0.17789328  0.090162701  0.265623868 0.0000004
OC-AS  0.15331748  0.022691061  0.283943900 0.0119510
SA-AS -0.03953343 -0.217121820  0.138054950 0.9739612
NA-EU  0.08289876  0.019858203  0.145939307 0.0030969
OC-EU  0.05832295 -0.057179072  0.173824975 0.6419270
SA-EU -0.13452796 -0.301306531  0.032250603 0.1793561
OC-NA -0.02457580 -0.131829800  0.082678193 0.9710618
SA-NA -0.21742672 -0.378602997 -0.056250441 0.0021848
SA-OC -0.19285092 -0.380851976 -0.004849855 0.0410993</code></pre>
</div>
</div>
</section>
<section id="review-again-tomorrow-1" class="level4">
<h4 class="anchored" data-anchor-id="review-again-tomorrow-1">Review again tomorrow</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>traits <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">'Openness'</span>, <span class="st">'Conscientiousness'</span>, <span class="st">'Extraversion'</span>, <span class="st">'Agreeableness'</span>, <span class="st">'Neuroticism'</span>)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (trait <span class="cf">in</span> traits) {</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">'</span><span class="sc">\n\n</span><span class="st">### ANOVA for'</span>, trait, <span class="st">'by Continent</span><span class="sc">\n\n</span><span class="st">'</span>)</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Group means</span></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>  means <span class="ot">&lt;-</span> bigfive_sample <span class="sc">%&gt;%</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(continent) <span class="sc">%&gt;%</span></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>(<span class="at">mean =</span> <span class="fu">mean</span>(.data[[trait]], <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(means)</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>  <span class="co"># ANOVA</span></span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>  model <span class="ot">&lt;-</span> <span class="fu">aov</span>(<span class="fu">as.formula</span>(<span class="fu">paste</span>(trait, <span class="st">'~ continent'</span>)), <span class="at">data =</span> bigfive_sample)</span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>  tidy_anova <span class="ot">&lt;-</span> <span class="fu">tidy</span>(model)</span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(</span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>    knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a>      tidy_anova,</span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="fu">paste</span>(<span class="st">'Table: ANOVA for'</span>, trait),</span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a>      <span class="at">digits =</span> <span class="dv">4</span></span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb24-21"><a href="#cb24-21" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb24-22"><a href="#cb24-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-23"><a href="#cb24-23" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Tukey HSD</span></span>
<span id="cb24-24"><a href="#cb24-24" aria-hidden="true" tabindex="-1"></a>  tukey <span class="ot">&lt;-</span> <span class="fu">TukeyHSD</span>(model)</span>
<span id="cb24-25"><a href="#cb24-25" aria-hidden="true" tabindex="-1"></a>  tukey_df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(tukey<span class="sc">$</span>continent)</span>
<span id="cb24-26"><a href="#cb24-26" aria-hidden="true" tabindex="-1"></a>  tukey_df<span class="sc">$</span>comparison <span class="ot">&lt;-</span> <span class="fu">rownames</span>(tukey_df)</span>
<span id="cb24-27"><a href="#cb24-27" aria-hidden="true" tabindex="-1"></a>  tukey_df <span class="ot">&lt;-</span> tukey_df <span class="sc">%&gt;%</span></span>
<span id="cb24-28"><a href="#cb24-28" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(comparison, diff, lwr, upr, <span class="st">`</span><span class="at">p adj</span><span class="st">`</span>)</span>
<span id="cb24-29"><a href="#cb24-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(</span>
<span id="cb24-30"><a href="#cb24-30" aria-hidden="true" tabindex="-1"></a>    knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb24-31"><a href="#cb24-31" aria-hidden="true" tabindex="-1"></a>      tukey_df,</span>
<span id="cb24-32"><a href="#cb24-32" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="fu">paste</span>(<span class="st">'Table: Tukey HSD for'</span>, trait),</span>
<span id="cb24-33"><a href="#cb24-33" aria-hidden="true" tabindex="-1"></a>      <span class="at">digits =</span> <span class="dv">4</span></span>
<span id="cb24-34"><a href="#cb24-34" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb24-35"><a href="#cb24-35" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb24-36"><a href="#cb24-36" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>

### ANOVA for Openness by Continent

# A tibble: 5 × 2
  continent  mean
  &lt;chr&gt;     &lt;dbl&gt;
1 AS         3.22
2 EU         3.35
3 NA         3.32
4 OC         3.31
5 SA         3.36


Table: Table: ANOVA for Openness

|term      |   df|    sumsq| meansq| statistic| p.value|
|:---------|----:|--------:|------:|---------:|-------:|
|continent |    4|   6.2662| 1.5666|   11.7464|       0|
|Residuals | 4835| 644.8236| 0.1334|        NA|      NA|


Table: Table: Tukey HSD for Openness

|      |comparison |    diff|     lwr|    upr|  p adj|
|:-----|:----------|-------:|-------:|------:|------:|
|EU-AS |EU-AS      |  0.1330|  0.0777| 0.1884| 0.0000|
|NA-AS |NA-AS      |  0.1090|  0.0593| 0.1588| 0.0000|
|OC-AS |OC-AS      |  0.0939|  0.0198| 0.1680| 0.0050|
|SA-AS |SA-AS      |  0.1469|  0.0462| 0.2476| 0.0007|
|NA-EU |NA-EU      | -0.0240| -0.0598| 0.0117| 0.3545|
|OC-EU |OC-EU      | -0.0391| -0.1046| 0.0264| 0.4777|
|SA-EU |SA-EU      |  0.0138| -0.0807| 0.1084| 0.9947|
|OC-NA |OC-NA      | -0.0151| -0.0759| 0.0457| 0.9611|
|SA-NA |SA-NA      |  0.0378| -0.0535| 0.1292| 0.7906|
|SA-OC |SA-OC      |  0.0530| -0.0536| 0.1596| 0.6559|


### ANOVA for Conscientiousness by Continent

# A tibble: 5 × 2
  continent  mean
  &lt;chr&gt;     &lt;dbl&gt;
1 AS         3.14
2 EU         3.11
3 NA         3.16
4 OC         3.08
5 SA         3.17


Table: Table: ANOVA for Conscientiousness

|term      |   df|    sumsq| meansq| statistic| p.value|
|:---------|----:|--------:|------:|---------:|-------:|
|continent |    4|   2.9218| 0.7305|    5.2751|   3e-04|
|Residuals | 4835| 669.5119| 0.1385|        NA|      NA|


Table: Table: Tukey HSD for Conscientiousness

|      |comparison |    diff|     lwr|     upr|  p adj|
|:-----|:----------|-------:|-------:|-------:|------:|
|EU-AS |EU-AS      | -0.0307| -0.0871|  0.0258| 0.5736|
|NA-AS |NA-AS      |  0.0155| -0.0352|  0.0662| 0.9200|
|OC-AS |OC-AS      | -0.0628| -0.1383|  0.0127| 0.1548|
|SA-AS |SA-AS      |  0.0227| -0.0799|  0.1253| 0.9744|
|NA-EU |NA-EU      |  0.0462|  0.0097|  0.0826| 0.0050|
|OC-EU |OC-EU      | -0.0321| -0.0989|  0.0346| 0.6827|
|SA-EU |SA-EU      |  0.0534| -0.0430|  0.1497| 0.5547|
|OC-NA |OC-NA      | -0.0783| -0.1403| -0.0163| 0.0052|
|SA-NA |SA-NA      |  0.0072| -0.0859|  0.1004| 0.9996|
|SA-OC |SA-OC      |  0.0855| -0.0231|  0.1941| 0.1999|


### ANOVA for Extraversion by Continent

# A tibble: 5 × 2
  continent  mean
  &lt;chr&gt;     &lt;dbl&gt;
1 AS         3.09
2 EU         2.99
3 NA         3.03
4 OC         3.02
5 SA         2.96


Table: Table: ANOVA for Extraversion

|term      |   df|    sumsq| meansq| statistic| p.value|
|:---------|----:|--------:|------:|---------:|-------:|
|continent |    4|   3.6350| 0.9087|    8.1323|       0|
|Residuals | 4835| 540.2897| 0.1117|        NA|      NA|


Table: Table: Tukey HSD for Extraversion

|      |comparison |    diff|     lwr|     upr|  p adj|
|:-----|:----------|-------:|-------:|-------:|------:|
|EU-AS |EU-AS      | -0.0935| -0.1442| -0.0428| 0.0000|
|NA-AS |NA-AS      | -0.0541| -0.0996| -0.0085| 0.0106|
|OC-AS |OC-AS      | -0.0648| -0.1326|  0.0030| 0.0693|
|SA-AS |SA-AS      | -0.1328| -0.2249| -0.0406| 0.0008|
|NA-EU |NA-EU      |  0.0394|  0.0067|  0.0721| 0.0090|
|OC-EU |OC-EU      |  0.0287| -0.0312|  0.0887| 0.6865|
|SA-EU |SA-EU      | -0.0393| -0.1258|  0.0473| 0.7290|
|OC-NA |OC-NA      | -0.0107| -0.0664|  0.0450| 0.9849|
|SA-NA |SA-NA      | -0.0787| -0.1624|  0.0050| 0.0767|
|SA-OC |SA-OC      | -0.0680| -0.1656|  0.0296| 0.3164|


### ANOVA for Agreeableness by Continent

# A tibble: 5 × 2
  continent  mean
  &lt;chr&gt;     &lt;dbl&gt;
1 AS         3.27
2 EU         3.13
3 NA         3.16
4 OC         3.15
5 SA         3.12


Table: Table: ANOVA for Agreeableness

|term      |   df|    sumsq| meansq| statistic| p.value|
|:---------|----:|--------:|------:|---------:|-------:|
|continent |    4|   6.8718| 1.7180|   14.9299|       0|
|Residuals | 4835| 556.3559| 0.1151|        NA|      NA|


Table: Table: Tukey HSD for Agreeableness

|      |comparison |    diff|     lwr|     upr|  p adj|
|:-----|:----------|-------:|-------:|-------:|------:|
|EU-AS |EU-AS      | -0.1422| -0.1936| -0.0907| 0.0000|
|NA-AS |NA-AS      | -0.1095| -0.1557| -0.0633| 0.0000|
|OC-AS |OC-AS      | -0.1157| -0.1845| -0.0469| 0.0000|
|SA-AS |SA-AS      | -0.1454| -0.2389| -0.0519| 0.0002|
|NA-EU |NA-EU      |  0.0327| -0.0005|  0.0659| 0.0565|
|OC-EU |OC-EU      |  0.0265| -0.0343|  0.0873| 0.7577|
|SA-EU |SA-EU      | -0.0032| -0.0911|  0.0846| 1.0000|
|OC-NA |OC-NA      | -0.0061| -0.0626|  0.0503| 0.9983|
|SA-NA |SA-NA      | -0.0359| -0.1208|  0.0490| 0.7779|
|SA-OC |SA-OC      | -0.0297| -0.1287|  0.0693| 0.9248|


### ANOVA for Neuroticism by Continent

# A tibble: 5 × 2
  continent  mean
  &lt;chr&gt;     &lt;dbl&gt;
1 AS         2.82
2 EU         2.91
3 NA         2.99
4 OC         2.97
5 SA         2.78


Table: Table: ANOVA for Neuroticism

|term      |   df|     sumsq| meansq| statistic| p.value|
|:---------|----:|---------:|------:|---------:|-------:|
|continent |    4|   19.3885| 4.8471|   11.6854|       0|
|Residuals | 4835| 2005.5627| 0.4148|        NA|      NA|


Table: Table: Tukey HSD for Neuroticism

|      |comparison |    diff|     lwr|     upr|  p adj|
|:-----|:----------|-------:|-------:|-------:|------:|
|EU-AS |EU-AS      |  0.0950| -0.0026|  0.1926| 0.0611|
|NA-AS |NA-AS      |  0.1779|  0.0902|  0.2656| 0.0000|
|OC-AS |OC-AS      |  0.1533|  0.0227|  0.2839| 0.0120|
|SA-AS |SA-AS      | -0.0395| -0.2171|  0.1381| 0.9740|
|NA-EU |NA-EU      |  0.0829|  0.0199|  0.1459| 0.0031|
|OC-EU |OC-EU      |  0.0583| -0.0572|  0.1738| 0.6419|
|SA-EU |SA-EU      | -0.1345| -0.3013|  0.0323| 0.1794|
|OC-NA |OC-NA      | -0.0246| -0.1318|  0.0827| 0.9711|
|SA-NA |SA-NA      | -0.2174| -0.3786| -0.0563| 0.0022|
|SA-OC |SA-OC      | -0.1929| -0.3809| -0.0048| 0.0411|</code></pre>
</div>
</div>
</section>
</section>
<section id="anova-result-review-later" class="level3">
<h3 class="anchored" data-anchor-id="anova-result-review-later">ANOVA Result (Review later)</h3>
<section id="openness" class="level4">
<h4 class="anchored" data-anchor-id="openness">Openness:</h4>
<p>ANOVA: F = 11.75, p &lt; .001 → significant overall difference.</p>
<p>Tukey: Asia (AS) significantly lower than all other continents (EU, NA, OC, SA).</p>
<p>EU–AS, NA–AS, OC–AS, SA–AS: all p &lt; .01.</p>
<p>Other pairs not significant.</p>
<p>Participants in Asia scored significantly lower on Openness than those from Europe, North America, Oceania, and South America. No other differences were significant.</p>
</section>
<section id="conscientiousness" class="level4">
<h4 class="anchored" data-anchor-id="conscientiousness">Conscientiousness</h4>
<p>ANOVA: F = 5.27, p &lt; .001 → significant.</p>
<p>Tukey: Only SA–AS is significant (p = .005).</p>
<p>South America mean = 3.17 → Asia mean = 3.14 → SA slightly higher.</p>
<p>NA–AS, EU–AS, other pairs → NS.</p>
<p>South America showed slightly higher Conscientiousness than Asia. No other pairs were significant.</p>
</section>
<section id="extraversion" class="level4">
<h4 class="anchored" data-anchor-id="extraversion">Extraversion</h4>
<p>ANOVA: F = 8.13, p &lt; .001 → significant.</p>
<p>Tukey:</p>
<p>EU–AS, NA–AS, SA–AS significant.</p>
<p>Other pairs → NS.</p>
<p>Asia scored significantly lower in Extraversion than Europe, North America, and South America.</p>
</section>
<section id="agreeableness" class="level4">
<h4 class="anchored" data-anchor-id="agreeableness">Agreeableness</h4>
<p>ANOVA: F = 14.93, p &lt; .001 → significant.</p>
<p>Tukey:</p>
<p>EU–AS, NA–AS, OC–AS, SA–AS → all significant.</p>
<p>Other pairs → NS.</p>
<p>Asia scored significantly lower in Agreeableness than Europe, North America, Oceania, and South America.</p>
</section>
<section id="neuroticism" class="level4">
<h4 class="anchored" data-anchor-id="neuroticism">Neuroticism</h4>
<p>ANOVA: F = 11.69, p &lt; .001 → significant.</p>
<p>Tukey:</p>
<p>NA–AS, OC–AS, SA–AS → significant.</p>
<p>SA–EU, SA–OC → significant.</p>
<p>Asia showed significantly lower Neuroticism than North America, Oceania, and South America. South America also scored significantly lower than Europe and Oceania. (Many pairs have small diffs)</p>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>